server:
  relay: "tcp://127.0.0.1:7000"
  command: "php ./vendor/bin/rr-worker start --relay-dsn tcp://127.0.0.1:7000"

http:
  address: 0.0.0.0:9090
  middleware: [ "headers", "gzip" ]
  pool:
    max_jobs: 64 # feel free to change this
    supervisor:
      exec_ttl: 60s
  headers:
    response:
      X-Powered-By: "RoadRunner"
  static:
    dir: "public"
    forbid: [ ".php" ]

#grpc:
#  listen: "tcp://:9001"
#  proto: "service.proto"
#  tls:
#    key:  "server.key"
#    cert: "server.crt"
#  workers:
#    command: "php worker.php"
#    pool:
#      numWorkers: 4
#
#metrics:
#  address: localhost:2112
#
#limit:
#  interval: 1
#  services:
#    grpc:
#      maxMemory: 100
#      TTL: 0
#      idleTTL: 0
#      execTTL: 60
